name: Package release 

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Sqa tag passed"
        required: true

jobs:
  check-rc-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: get rc build number 
        run: |  
          git fetch --tags
          latest_rc_tag=$(git tag --sort=committerdate | tail -1 || echo "error")
          echo "latest_rc_tag: $latest_rc_tag"
          if [ "$latest_rc_tag" != "error" ] && [ -n "$latest_rc_tag" ]; then
            current_rc_number=$(echo "$latest_rc_tag" | sed -n 's/^.*-rc\([^.]*\)\..*$/\1/p')
            echo "rc_number=$(expr $current_rc_number + 1)"  >> $GITHUB_ENV 
          else
            echo "Latest RC Tag is empty or not found."
            echo "rc_number=1" >> $GITHUB_ENV 
          fi
    outputs:
      rc_build_number: ${{ env.rc_number }}
      
  get-tag-version:
    runs-on: ubuntu-latest
    needs: check-rc-build
    steps:
      - name: create release branch name and tag
        run: |
          major_version=$(echo "${{ inputs.tag }}" | cut -d'.' -f1)
          minor_version=$(echo "$${{ inputs.tag }}" | cut -d'.' -f2)
          full_version=$(echo "${{ inputs.tag }}" | cut -d'-' -f1)
          echo "release_branch_name=Release/v$major_version.$minor_version" >> $GITHUB_ENV 
          echo "release_tag=v$full_version-rc${{ needs.check-rc-build.outputs.rc_build_number }}.${{ github.run_number }}" >> $GITHUB_ENV 
          echo "major_version:$major_version minor_version:$minor_version  full_version:$full_version  release_branch_name:$release_branch_name release_tag:$release_tag"
    outputs:
      release_branch_name: ${{ env.release_branch_name }}
      release_tag: ${{ env.release_tag }}
      
  release-package:
    runs-on: ubuntu-latest
    needs: get-tag-version 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create release branch from tag
        run: |
           echo "a: ${{ needs.get-tag-version.outputs.release_branch_name }} b: ${{ needs.get-tag-version.outputs.release_tag }}"
           git checkout -b ${{ needs.get-tag-version.outputs.release_branch_name }}
           git push origin ${{ needs.get-tag-version.outputs.release_branch_name }}

      
      - name: Create release tag
        run: |
          git tag ${{ needs.get-tag-version.outputs.release_tag }}
          git push origin ${{ needs.get-tag-version.outputs.release_tag }}

