name: abckithegayic


on:
  workflow_dispatch:
    inputs:
      commit_ids:
        description: 'List of commit IDs to merge (separated by comma)'
        required: true


jobs:
  merge_commits:
    runs-on: runner_160_1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

           
      - name: Merge Commits
        run: |
          commit_ids="${{ github.event.inputs.commit_ids }}"
          git checkout -b feature/feature-name origin/Release/v1.0
          git fetch --all
          git fetch main
          git cherry-pick 1e6ae41da854b8e6e793f33fa3c63c3ef2575bca
          git push origin feature/feature-name
