name: abckithegayic


on:
  workflow_dispatch:
    inputs:
      commit_ids:
        description: 'List of commit IDs to merge (separated by comma)'
        required: true


jobs:
  # merge_commits:
  #   runs-on: runner_160_1
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

           
  #     - name: Merge Commits
  #       run: |
  #         commit_ids="${{ github.event.inputs.commit_ids }}"
  #         git checkout -b feature/feature-name origin/Release/v1.0
  #         git fetch --all
  #         git fetch origin main
  #         git log main 
  #         git show 1e6ae41da854b8e6e793f33fa3c63c3ef2575bca
  #         echo "yaha tk"
  #         git cherry-pick 1e6ae41da854b8e6e793f33fa3c63c3ef2575bca
  #         git push origin feature/feature-name

  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const { context, github } = require('@actions/github');
            const branch = context.ref.split('/').pop();
            const pr = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: ⁠ Hotfix for release/${branch} ⁠,
              head: ⁠ Release/v1.0 ⁠,
              base: ⁠ Release/v2.0 ⁠,
              body: ⁠ This PR contains hotfix changes for release/${branch}. ⁠
            });
            console.log(⁠ Pull request created: ${pr.data.html_url} ⁠); 
