name: Merge to release/1.0

on:
  push:
    branches:
      - 'release/1.0'

jobs:
  merge_to_release:
    name: Merge to release/1.0
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
