name: Monitor PR Merges

on:
  pull_request:
    types:
      - closed
    branches:
      - 'Release/v1.0'
jobs:
  print_workflow_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print Workflow Name
        run: |
          echo "repo ${{ github.repository }} $(echo ${GITHUB_REF#refs/heads/})"
          git fetch
          a=$(git rev-parse origin/Release/v1.0)
          echo "hey id $a"
          git show --format=%B $a
          version=$(git show --format=%B $a | grep -oP 'version\s+\K\S+')
          rc=$(git show --format=%B $a | grep -oP 'rc\s+\K\S+')
          echo "hey id $a $version $rc"
