name: Monitor PR Merges

on:
  workflow_call:
  push:
    branches:
      - 'release/v1.0'
jobs:

  validate_condition_for_onpush:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.pull_request.head.ref == 'prerelease'
    steps:
      - name: Check  branch
        run: |
          echo  "hello $github.event.pull_request.head.ref"
          exit 1

  print_workflow_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print Workflow Name
        run: |
          echo "repo ${{ github.repository }} $(echo ${GITHUB_REF#refs/heads/})"
          git fetch
          git branch 
          a=$(git rev-parse origin/${GITHUB_REF#refs/heads/})
          echo "hey id $a"
          git show --format=%B $a
          version=$(git show --format=%B $a | grep -oP 'version\s+\K\S+')
          rc=$(git show --format=%B $a | grep -oP 'rc\s+\K\S+')
          echo "hey id $a $version $rc"
          ls 
          cat releasefile.txt
